spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/ventura2024

server:
  port: 8111

jjwt:
  secret: 4u7x!A%D*G-KaNdRgUkXp2s5v8y/B?E(H+MbQeShVmYq3t6w9z$C&F)J@NcRfUjW
  expiration: 2800
